package net.sen.sens_scifi_stuff.datagen.recipes;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.RecipeOutput;
import net.minecraft.world.item.Items;
import net.sen.sens_scifi_stuff.blocks.ModBlocks;
import net.sen.sens_scifi_stuff.items.ModItems;

import java.util.concurrent.CompletableFuture;

public class ModRecipeProvider extends ModRecipeHelper {
    public ModRecipeProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> registries) {
        super(output, registries);
    }

    @Override
    protected void buildRecipes(RecipeOutput output) {
        this.vanillaMetalRecipes(output, Items.IRON_INGOT, ModItems.PURE_RAW_IRON_ITEM.get(), ModBlocks.PURE_RAW_IRON_BLOCK.get(), ModItems.REFINED_IRON_INGOT_ITEM.get(), ModBlocks.REFINED_IRON_BLOCK.get(), ModItems.REFINED_IRON_NUGGET_ITEM.get(), ModItems.IRON_DUST_ITEM.get(), ModItems.REFINED_IRON_DUST_ITEM.get(), ModItems.REFINED_IRON_SWORD_ITEM.get(), ModItems.REFINED_IRON_AXE_ITEM.get(), ModItems.REFINED_IRON_SHOVEL_ITEM.get(), ModItems.REFINED_IRON_PICKAXE_ITEM.get(), ModItems.REFINED_IRON_HOE_ITEM.get(), ModItems.REFINED_IRON_SHIELD_ITEM.get(), ModItems.REFINED_IRON_BOOTS_ITEM.get(), ModItems.REFINED_IRON_LEGGINGS_ITEM.get(), ModItems.REFINED_IRON_CHESTPLATE_ITEM.get(), ModItems.REFINED_IRON_HELMET_ITEM.get());
        this.vanillaMetalRecipes(output, Items.COPPER_INGOT, ModItems.PURE_RAW_COPPER_ITEM.get(), ModBlocks.PURE_RAW_COPPER_BLOCK.get(), ModItems.REFINED_COPPER_INGOT_ITEM.get(), ModBlocks.REFINED_COPPER_BLOCK.get(), ModItems.REFINED_COPPER_NUGGET_ITEM.get(), ModItems.COPPER_DUST_ITEM.get(), ModItems.REFINED_COPPER_DUST_ITEM.get(), ModItems.REFINED_COPPER_SWORD_ITEM.get(), ModItems.REFINED_COPPER_AXE_ITEM.get(), ModItems.REFINED_COPPER_SHOVEL_ITEM.get(), ModItems.REFINED_COPPER_PICKAXE_ITEM.get(), ModItems.REFINED_COPPER_HOE_ITEM.get(), ModItems.REFINED_COPPER_SHIELD_ITEM.get(), ModItems.REFINED_COPPER_BOOTS_ITEM.get(), ModItems.REFINED_COPPER_LEGGINGS_ITEM.get(), ModItems.REFINED_COPPER_CHESTPLATE_ITEM.get(), ModItems.REFINED_COPPER_HELMET_ITEM.get());
        this.vanillaMetalRecipes(output, Items.GOLD_INGOT, ModItems.PURE_RAW_GOLD_ITEM.get(), ModBlocks.PURE_RAW_GOLD_BLOCK.get(), ModItems.REFINED_GOLD_INGOT_ITEM.get(), ModBlocks.REFINED_GOLD_BLOCK.get(), ModItems.REFINED_GOLD_NUGGET_ITEM.get(), ModItems.GOLD_DUST_ITEM.get(), ModItems.REFINED_GOLD_DUST_ITEM.get(), ModItems.REFINED_GOLD_SWORD_ITEM.get(), ModItems.REFINED_GOLD_AXE_ITEM.get(), ModItems.REFINED_GOLD_SHOVEL_ITEM.get(), ModItems.REFINED_GOLD_PICKAXE_ITEM.get(), ModItems.REFINED_GOLD_HOE_ITEM.get(), ModItems.REFINED_GOLD_SHIELD_ITEM.get(), ModItems.REFINED_GOLD_BOOTS_ITEM.get(), ModItems.REFINED_GOLD_LEGGINGS_ITEM.get(), ModItems.REFINED_GOLD_CHESTPLATE_ITEM.get(), ModItems.REFINED_GOLD_HELMET_ITEM.get());

        this.metalRecipes(output, ModBlocks.ORE_TIN_BLOCK.get(), ModItems.RAW_TIN_ITEM.get(), ModBlocks.RAW_TIN_BLOCK.get(), ModItems.PURE_RAW_TIN_ITEM.get(), ModBlocks.PURE_RAW_TIN_BLOCK.get(), ModItems.TIN_INGOT_ITEM.get(), ModBlocks.TIN_BLOCK.get(), ModItems.REFINED_TIN_INGOT_ITEM.get(), ModBlocks.REFINED_TIN_BLOCK.get(), ModItems.TIN_NUGGET_ITEM.get(), ModItems.REFINED_TIN_NUGGET_ITEM.get(), ModItems.TIN_DUST_ITEM.get(), ModItems.REFINED_TIN_DUST_ITEM.get(), ModItems.TIN_SWORD_ITEM.get(), ModItems.TIN_AXE_ITEM.get(), ModItems.TIN_SHOVEL_ITEM.get(), ModItems.TIN_PICKAXE_ITEM.get(), ModItems.TIN_HOE_ITEM.get(), ModItems.TIN_SHIELD_ITEM.get(), ModItems.TIN_BOOTS_ITEM.get(), ModItems.TIN_LEGGINGS_ITEM.get(), ModItems.TIN_CHESTPLATE_ITEM.get(), ModItems.TIN_HELMET_ITEM.get(), ModItems.REFINED_TIN_SWORD_ITEM.get(), ModItems.REFINED_TIN_AXE_ITEM.get(), ModItems.REFINED_TIN_SHOVEL_ITEM.get(), ModItems.REFINED_TIN_PICKAXE_ITEM.get(), ModItems.REFINED_TIN_HOE_ITEM.get(), ModItems.REFINED_TIN_SHIELD_ITEM.get(), ModItems.REFINED_TIN_BOOTS_ITEM.get(), ModItems.REFINED_TIN_LEGGINGS_ITEM.get(), ModItems.REFINED_TIN_CHESTPLATE_ITEM.get(), ModItems.REFINED_TIN_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_ZINC_BLOCK.get(), ModItems.RAW_ZINC_ITEM.get(), ModBlocks.RAW_ZINC_BLOCK.get(), ModItems.PURE_RAW_ZINC_ITEM.get(), ModBlocks.PURE_RAW_ZINC_BLOCK.get(), ModItems.ZINC_INGOT_ITEM.get(), ModBlocks.ZINC_BLOCK.get(), ModItems.REFINED_ZINC_INGOT_ITEM.get(), ModBlocks.REFINED_ZINC_BLOCK.get(), ModItems.ZINC_NUGGET_ITEM.get(), ModItems.REFINED_ZINC_NUGGET_ITEM.get(), ModItems.ZINC_DUST_ITEM.get(), ModItems.REFINED_ZINC_DUST_ITEM.get(), ModItems.ZINC_SWORD_ITEM.get(), ModItems.ZINC_AXE_ITEM.get(), ModItems.ZINC_SHOVEL_ITEM.get(), ModItems.ZINC_PICKAXE_ITEM.get(), ModItems.ZINC_HOE_ITEM.get(), ModItems.ZINC_SHIELD_ITEM.get(), ModItems.ZINC_BOOTS_ITEM.get(), ModItems.ZINC_LEGGINGS_ITEM.get(), ModItems.ZINC_CHESTPLATE_ITEM.get(), ModItems.ZINC_HELMET_ITEM.get(), ModItems.REFINED_ZINC_SWORD_ITEM.get(), ModItems.REFINED_ZINC_AXE_ITEM.get(), ModItems.REFINED_ZINC_SHOVEL_ITEM.get(), ModItems.REFINED_ZINC_PICKAXE_ITEM.get(), ModItems.REFINED_ZINC_HOE_ITEM.get(), ModItems.REFINED_ZINC_SHIELD_ITEM.get(), ModItems.REFINED_ZINC_BOOTS_ITEM.get(), ModItems.REFINED_ZINC_LEGGINGS_ITEM.get(), ModItems.REFINED_ZINC_CHESTPLATE_ITEM.get(), ModItems.REFINED_ZINC_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_NICKEL_BLOCK.get(), ModItems.RAW_NICKEL_ITEM.get(), ModBlocks.RAW_NICKEL_BLOCK.get(), ModItems.PURE_RAW_NICKEL_ITEM.get(), ModBlocks.PURE_RAW_NICKEL_BLOCK.get(), ModItems.NICKEL_INGOT_ITEM.get(), ModBlocks.NICKEL_BLOCK.get(), ModItems.REFINED_NICKEL_INGOT_ITEM.get(), ModBlocks.REFINED_NICKEL_BLOCK.get(), ModItems.NICKEL_NUGGET_ITEM.get(), ModItems.REFINED_NICKEL_NUGGET_ITEM.get(), ModItems.NICKEL_DUST_ITEM.get(), ModItems.REFINED_NICKEL_DUST_ITEM.get(), ModItems.NICKEL_SWORD_ITEM.get(), ModItems.NICKEL_AXE_ITEM.get(), ModItems.NICKEL_SHOVEL_ITEM.get(), ModItems.NICKEL_PICKAXE_ITEM.get(), ModItems.NICKEL_HOE_ITEM.get(), ModItems.NICKEL_SHIELD_ITEM.get(), ModItems.NICKEL_BOOTS_ITEM.get(), ModItems.NICKEL_LEGGINGS_ITEM.get(), ModItems.NICKEL_CHESTPLATE_ITEM.get(), ModItems.NICKEL_HELMET_ITEM.get(), ModItems.REFINED_NICKEL_SWORD_ITEM.get(), ModItems.REFINED_NICKEL_AXE_ITEM.get(), ModItems.REFINED_NICKEL_SHOVEL_ITEM.get(), ModItems.REFINED_NICKEL_PICKAXE_ITEM.get(), ModItems.REFINED_NICKEL_HOE_ITEM.get(), ModItems.REFINED_NICKEL_SHIELD_ITEM.get(), ModItems.REFINED_NICKEL_BOOTS_ITEM.get(), ModItems.REFINED_NICKEL_LEGGINGS_ITEM.get(), ModItems.REFINED_NICKEL_CHESTPLATE_ITEM.get(), ModItems.REFINED_NICKEL_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_LEAD_BLOCK.get(), ModItems.RAW_LEAD_ITEM.get(), ModBlocks.RAW_LEAD_BLOCK.get(), ModItems.PURE_RAW_LEAD_ITEM.get(), ModBlocks.PURE_RAW_LEAD_BLOCK.get(), ModItems.LEAD_INGOT_ITEM.get(), ModBlocks.LEAD_BLOCK.get(), ModItems.REFINED_LEAD_INGOT_ITEM.get(), ModBlocks.REFINED_LEAD_BLOCK.get(), ModItems.LEAD_NUGGET_ITEM.get(), ModItems.REFINED_LEAD_NUGGET_ITEM.get(), ModItems.LEAD_DUST_ITEM.get(), ModItems.REFINED_LEAD_DUST_ITEM.get(), ModItems.LEAD_SWORD_ITEM.get(), ModItems.LEAD_AXE_ITEM.get(), ModItems.LEAD_SHOVEL_ITEM.get(), ModItems.LEAD_PICKAXE_ITEM.get(), ModItems.LEAD_HOE_ITEM.get(), ModItems.LEAD_SHIELD_ITEM.get(), ModItems.LEAD_BOOTS_ITEM.get(), ModItems.LEAD_LEGGINGS_ITEM.get(), ModItems.LEAD_CHESTPLATE_ITEM.get(), ModItems.LEAD_HELMET_ITEM.get(), ModItems.REFINED_LEAD_SWORD_ITEM.get(), ModItems.REFINED_LEAD_AXE_ITEM.get(), ModItems.REFINED_LEAD_SHOVEL_ITEM.get(), ModItems.REFINED_LEAD_PICKAXE_ITEM.get(), ModItems.REFINED_LEAD_HOE_ITEM.get(), ModItems.REFINED_LEAD_SHIELD_ITEM.get(), ModItems.REFINED_LEAD_BOOTS_ITEM.get(), ModItems.REFINED_LEAD_LEGGINGS_ITEM.get(), ModItems.REFINED_LEAD_CHESTPLATE_ITEM.get(), ModItems.REFINED_LEAD_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_INVAR_BLOCK.get(), ModItems.RAW_INVAR_ITEM.get(), ModBlocks.RAW_INVAR_BLOCK.get(), ModItems.PURE_RAW_INVAR_ITEM.get(), ModBlocks.PURE_RAW_INVAR_BLOCK.get(), ModItems.INVAR_INGOT_ITEM.get(), ModBlocks.INVAR_BLOCK.get(), ModItems.REFINED_INVAR_INGOT_ITEM.get(), ModBlocks.REFINED_INVAR_BLOCK.get(), ModItems.INVAR_NUGGET_ITEM.get(), ModItems.REFINED_INVAR_NUGGET_ITEM.get(), ModItems.INVAR_DUST_ITEM.get(), ModItems.REFINED_INVAR_DUST_ITEM.get(), ModItems.INVAR_SWORD_ITEM.get(), ModItems.INVAR_AXE_ITEM.get(), ModItems.INVAR_SHOVEL_ITEM.get(), ModItems.INVAR_PICKAXE_ITEM.get(), ModItems.INVAR_HOE_ITEM.get(), ModItems.INVAR_SHIELD_ITEM.get(), ModItems.INVAR_BOOTS_ITEM.get(), ModItems.INVAR_LEGGINGS_ITEM.get(), ModItems.INVAR_CHESTPLATE_ITEM.get(), ModItems.INVAR_HELMET_ITEM.get(), ModItems.REFINED_INVAR_SWORD_ITEM.get(), ModItems.REFINED_INVAR_AXE_ITEM.get(), ModItems.REFINED_INVAR_SHOVEL_ITEM.get(), ModItems.REFINED_INVAR_PICKAXE_ITEM.get(), ModItems.REFINED_INVAR_HOE_ITEM.get(), ModItems.REFINED_INVAR_SHIELD_ITEM.get(), ModItems.REFINED_INVAR_BOOTS_ITEM.get(), ModItems.REFINED_INVAR_LEGGINGS_ITEM.get(), ModItems.REFINED_INVAR_CHESTPLATE_ITEM.get(), ModItems.REFINED_INVAR_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_SILVER_BLOCK.get(), ModItems.RAW_SILVER_ITEM.get(), ModBlocks.RAW_SILVER_BLOCK.get(), ModItems.PURE_RAW_SILVER_ITEM.get(), ModBlocks.PURE_RAW_SILVER_BLOCK.get(), ModItems.SILVER_INGOT_ITEM.get(), ModBlocks.SILVER_BLOCK.get(), ModItems.REFINED_SILVER_INGOT_ITEM.get(), ModBlocks.REFINED_SILVER_BLOCK.get(), ModItems.SILVER_NUGGET_ITEM.get(), ModItems.REFINED_SILVER_NUGGET_ITEM.get(), ModItems.SILVER_DUST_ITEM.get(), ModItems.REFINED_SILVER_DUST_ITEM.get(), ModItems.SILVER_SWORD_ITEM.get(), ModItems.SILVER_AXE_ITEM.get(), ModItems.SILVER_SHOVEL_ITEM.get(), ModItems.SILVER_PICKAXE_ITEM.get(), ModItems.SILVER_HOE_ITEM.get(), ModItems.SILVER_SHIELD_ITEM.get(), ModItems.SILVER_BOOTS_ITEM.get(), ModItems.SILVER_LEGGINGS_ITEM.get(), ModItems.SILVER_CHESTPLATE_ITEM.get(), ModItems.SILVER_HELMET_ITEM.get(), ModItems.REFINED_SILVER_SWORD_ITEM.get(), ModItems.REFINED_SILVER_AXE_ITEM.get(), ModItems.REFINED_SILVER_SHOVEL_ITEM.get(), ModItems.REFINED_SILVER_PICKAXE_ITEM.get(), ModItems.REFINED_SILVER_HOE_ITEM.get(), ModItems.REFINED_SILVER_SHIELD_ITEM.get(), ModItems.REFINED_SILVER_BOOTS_ITEM.get(), ModItems.REFINED_SILVER_LEGGINGS_ITEM.get(), ModItems.REFINED_SILVER_CHESTPLATE_ITEM.get(), ModItems.REFINED_SILVER_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_ELECTRUM_BLOCK.get(), ModItems.RAW_ELECTRUM_ITEM.get(), ModBlocks.RAW_ELECTRUM_BLOCK.get(), ModItems.PURE_RAW_ELECTRUM_ITEM.get(), ModBlocks.PURE_RAW_ELECTRUM_BLOCK.get(), ModItems.ELECTRUM_INGOT_ITEM.get(), ModBlocks.ELECTRUM_BLOCK.get(), ModItems.REFINED_ELECTRUM_INGOT_ITEM.get(), ModBlocks.REFINED_ELECTRUM_BLOCK.get(), ModItems.ELECTRUM_NUGGET_ITEM.get(), ModItems.REFINED_ELECTRUM_NUGGET_ITEM.get(), ModItems.ELECTRUM_DUST_ITEM.get(), ModItems.REFINED_ELECTRUM_DUST_ITEM.get(), ModItems.ELECTRUM_SWORD_ITEM.get(), ModItems.ELECTRUM_AXE_ITEM.get(), ModItems.ELECTRUM_SHOVEL_ITEM.get(), ModItems.ELECTRUM_PICKAXE_ITEM.get(), ModItems.ELECTRUM_HOE_ITEM.get(), ModItems.ELECTRUM_SHIELD_ITEM.get(), ModItems.ELECTRUM_BOOTS_ITEM.get(), ModItems.ELECTRUM_LEGGINGS_ITEM.get(), ModItems.ELECTRUM_CHESTPLATE_ITEM.get(), ModItems.ELECTRUM_HELMET_ITEM.get(), ModItems.REFINED_ELECTRUM_SWORD_ITEM.get(), ModItems.REFINED_ELECTRUM_AXE_ITEM.get(), ModItems.REFINED_ELECTRUM_SHOVEL_ITEM.get(), ModItems.REFINED_ELECTRUM_PICKAXE_ITEM.get(), ModItems.REFINED_ELECTRUM_HOE_ITEM.get(), ModItems.REFINED_ELECTRUM_SHIELD_ITEM.get(), ModItems.REFINED_ELECTRUM_BOOTS_ITEM.get(), ModItems.REFINED_ELECTRUM_LEGGINGS_ITEM.get(), ModItems.REFINED_ELECTRUM_CHESTPLATE_ITEM.get(), ModItems.REFINED_ELECTRUM_HELMET_ITEM.get());
        this.metalRecipes(output, ModBlocks.ORE_URANIUM_BLOCK.get(), ModItems.RAW_URANIUM_ITEM.get(), ModBlocks.RAW_URANIUM_BLOCK.get(), ModItems.PURE_RAW_URANIUM_ITEM.get(), ModBlocks.PURE_RAW_URANIUM_BLOCK.get(), ModItems.URANIUM_INGOT_ITEM.get(), ModBlocks.URANIUM_BLOCK.get(), ModItems.REFINED_URANIUM_INGOT_ITEM.get(), ModBlocks.REFINED_URANIUM_BLOCK.get(), ModItems.URANIUM_NUGGET_ITEM.get(), ModItems.REFINED_URANIUM_NUGGET_ITEM.get(), ModItems.URANIUM_DUST_ITEM.get(), ModItems.REFINED_URANIUM_DUST_ITEM.get());

        this.alloyRecipes(output, ModItems.RAW_STEEL_MIX_ITEM.get(), ModItems.STEEL_INGOT_ITEM.get(), ModBlocks.STEEL_BLOCK.get(), ModItems.STEEL_INGOT_ITEM.get(), ModItems.STEEL_DUST_ITEM.get(), ModItems.STEEL_SWORD_ITEM.get(), ModItems.STEEL_AXE_ITEM.get(), ModItems.STEEL_SHOVEL_ITEM.get(), ModItems.STEEL_PICKAXE_ITEM.get(), ModItems.STEEL_HOE_ITEM.get(), ModItems.STEEL_SHIELD_ITEM.get(), ModItems.STEEL_BOOTS_ITEM.get(), ModItems.STEEL_LEGGINGS_ITEM.get(), ModItems.STEEL_CHESTPLATE_ITEM.get(), ModItems.STEEL_HELMET_ITEM.get());
        this.alloyRecipes(output, ModItems.RAW_BRONZE_MIX_ITEM.get(), ModItems.BRONZE_INGOT_ITEM.get(), ModBlocks.BRONZE_BLOCK.get(), ModItems.BRONZE_INGOT_ITEM.get(), ModItems.BRONZE_DUST_ITEM.get(), ModItems.BRONZE_SWORD_ITEM.get(), ModItems.BRONZE_AXE_ITEM.get(), ModItems.BRONZE_SHOVEL_ITEM.get(), ModItems.BRONZE_PICKAXE_ITEM.get(), ModItems.BRONZE_HOE_ITEM.get(), ModItems.BRONZE_SHIELD_ITEM.get(), ModItems.BRONZE_BOOTS_ITEM.get(), ModItems.BRONZE_LEGGINGS_ITEM.get(), ModItems.BRONZE_CHESTPLATE_ITEM.get(), ModItems.BRONZE_HELMET_ITEM.get());
        this.alloyRecipes(output, ModItems.RAW_BRASS_MIX_ITEM.get(), ModItems.BRASS_INGOT_ITEM.get(), ModBlocks.BRASS_BLOCK.get(), ModItems.BRASS_INGOT_ITEM.get(), ModItems.BRASS_DUST_ITEM.get(), ModItems.BRASS_SWORD_ITEM.get(), ModItems.BRASS_AXE_ITEM.get(), ModItems.BRASS_SHOVEL_ITEM.get(), ModItems.BRASS_PICKAXE_ITEM.get(), ModItems.BRASS_HOE_ITEM.get(), ModItems.BRASS_SHIELD_ITEM.get(), ModItems.BRASS_BOOTS_ITEM.get(), ModItems.BRASS_LEGGINGS_ITEM.get(), ModItems.BRASS_CHESTPLATE_ITEM.get(), ModItems.BRASS_HELMET_ITEM.get());
    }
}
